version: '3.8'

networks:
  login-service:
    driver: bridge

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/usr/app/src
    environment:
      PORT: "4000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - login-service

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/user/app/src
      - ./client/public:/user/app/public
      - ./client/types:/user/app/types
    tty: true
    stdin_open: true
    environment:
      CLIENT_PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - login-service

  webserver:
    image: nginx:1.21.6-alpine
    ports:
      - 8080:80
    volumes:
      - ./infrastructure/webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
    networks:
      - login-service

  db:
    image: mongo:4.0.28-xenial
    restart: always
    volumes:
      - ./infrastructure/db/data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: app_db
    networks:
      - login-service

  db-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_SERVER: db
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
        ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    networks:
      - login-service
    depends_on:
      - db