version: '3.8'

networks:
  login-service:
    driver: bridge

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/usr/app/src
    environment:
      PORT: "4000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - login-service

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/user/app/src
      - ./client/public:/user/app/public
      - ./client/types:/user/app/types
    tty: true
    stdin_open: true
    environment:
      CLIENT_PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - login-service

  webserver:
    image: nginx:1.21.6-alpine
    ports:
      - 8080:80
    volumes:
      - ./infrastructure/webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
    networks:
      - login-service
